# Generated by Django 3.1.4 on 2020-12-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='intro',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurantImage')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RestaurantImages', to='restaurants.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='main_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_img', to='restaurants.restaurantimage'),
        ),
    ]
